version: '3.7'
services:
  db:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    volumes:
     - ./database/data:/var/lib/mysql
     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - intranet

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v0.7.1-alpha.1
    environment:
      - DSN=mysql://root:root@tcp(db:3306)/test?max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.7.1-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=mysql://root:root@tcp(db:3306)/test?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet
networks:
  intranet:
